JSgames/urls.py
from django.urls import path
from JSgames.views import chessGame
app_name="JSgames"
urlpatterns=[
    path('chessGame',chessGame,name="chessGame"),
]

news/urls.py
from django.urls import path
from .views import homeNews,ArticoloDetailViewCB,ArticoloListView,GiornalistaListView,GiornalistaDetailViewCB #articoloDetailView

app_name="news"

urlpatterns = [
    path('',homeNews,name="homeNews"),
    #path('articoli/<int:pk>',articoloDetailView,name='articolo_detail'),
    path("articoli/<int:pk>",ArticoloDetailViewCB.as_view(),name="articolo_detail"),
    path('lista_articoli/',ArticoloListView.as_view(),name='lista_articoli'),
    path('lista_giornalisti/',GiornalistaListView.as_view(),name='lista_giornalisti'),
    path('gionalisti/<int:pk>',GiornalistaDetailViewCB.as_view(),name="giornalista_detail")
]

prima_app/urls.py
from django.urls import path
from prima_app.views import homepage
from prima_app.views import welcome
from prima_app.views import lista
from prima_app.views import chi_siamo
from prima_app.views import variabili
from prima_app.views import index

app_name="prima_app"
urlpatterns=[
    path('homepage',homepage,name="homepage"),
    path('welcome',welcome,name="welcome"),
    path('lista',lista,name="lista"),
    path('chi_siamo',chi_siamo,name="chi_siamo"),
    path('variabili',variabili,name="variabili"),
    path('',index,name="index"),
]

primo_progetto/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("prima_app.urls",namespace="prima_app")),
    path('seconda_app/',include("seconda_app.urls",namespace="seconda_app")),
    path('news/',include("news.urls",namespace="news")),
    path('JSgames/',include("JSgames.urls",namespace="JSgames")),
    path('prova_pratica_1/',include("prova_pratica_1.urls",namespace="prova_pratica_1")),
]

prova_pratica_1/urls.py
from django.urls.conf import path
from django.urls import path
from prova_pratica_1.views import view_b,view_c,lista_materie,json_version

app_name="prova_pratica_1"
urlpatterns = [
    path('view_b',view_b,name="view_b"),
    path('view_c',view_c,name="view_c"),
    path('lista_materie',lista_materie,name="lista_materie"),
    path('json_version',json_version,name="json_version"),
]

seconda_app/urls.py
from django.urls.conf import path
from django.urls import path
from seconda_app.views import es_if
from seconda_app.views import if_else_elif
from seconda_app.views import es_for

app_name="seconda_app"
urlpatterns = [
    path('es_if',es_if,name="es_if"),
    path('if_else_elif',if_else_elif,name="if_else_elif"),
    path('es_for',es_for,name="es_for"),
]

JSgames/models.py
from django.db import models

# Create your models here.

news/models.py
from django.db import models
from django.db.models.deletion import CASCADE

# Create your models here.
class Giornalista(models.Model):
    nome=models.CharField(max_length=20)
    cognome=models.CharField(max_length=20)
    
    def __str__(self):
        return self.nome+""+self.cognome

class Articolo(models.Model):
    titolo = models.CharField(max_length=100)
    contenuto=models.TextField()
    giornalista=models.ForeignKey(Giornalista, on_delete=models.CASCADE, related_name="articoli")

    def __str__(self):
        return self.titolo

class Meta:
    verbose_name="Giornalista"
    varbose_name_plural="Giornalisti"
class Meta:
    verbose_name="Articolo"
    varbose_name_plural="Articoli"

prova_pratica_1/models.py
# Create your models here.

JSgames/views.py
from django.shortcuts import render

# Create your views here.
def chessGame(request):
    return render(request, "chessGame.html")

news/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, response
from .models import Articolo,Giornalista
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
# Create your views here.
def homeNews(request):
    articoli=Articolo.objects.all()
    giornalisti=Giornalista.objects.all()
    context={"articoli":articoli,"giornalisti":giornalisti}
    print(context)
    return render(request,"homeNews.html",context)

def articoloDetailView(request,pk):
    articolo=get_object_or_404(Articolo,pk=pk)
    context={"articolo":articolo}
    return render(request,'articolo_detail.html',context)

class ArticoloDetailViewCB(DetailView):
    model=Articolo
    template_name="articolo_detail.html"

class ArticoloListView(ListView):
    model=Articolo
    template_name='lista_articoli.html'
    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)
        context['articoli']=Articolo.objects.all()
        return context
class GiornalistaListView(ListView):
    model=Giornalista
    template_name='lista_giornalisti.html'
    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)
        context['giornalisti']=Giornalista.objects.all()
        return context
class GiornalistaDetailViewCB(DetailView):
    model=Giornalista
    template_name="giornalista_detail.html"

prima_app/views.py
from django.shortcuts import render

# Create your views here.
def homepage(request):
    return render(request,"homepage.html")
def welcome(request):
    return render(request,"welcome.html")
def lista(request):
    return render(request,"lista.html")
def chi_siamo(request):
    return render(request,"chi_siamo.html")
def variabili(request):
    context={
        'var1':'Prima variabile',
        'var2':'Seconda variabile',
        'var3':'Terza variabile'
    }
    return render(request,"variabili.html",context)
def index(request):
    return render(request,"index.html")

prova_pratica_1/views.py
from multiprocessing import context
from urllib import response
from django.http import JsonResponse
from django.shortcuts import render

# Create your views here.
def view_b(request):
    materie={
        'm1':"Matematica",
        'm2':"Italiano",
        'm3':"Inglese",
        'm4':"Storia",
        'm5':"Geografia"
    }
    return render(request,"view_b.html",materie)
def view_c(request):
    context = {
        'GiuseppeGullo':[["Matematica",9,0],("Italiano",7,3),("Inglese",7.5,4),("Storia",7.5,4),("Geografia",5,7)],
        'AntonioBarbera':[("Matematica",8,1),("Italiano",6,1),("Inglese",9.5,0),("Storia",8,2),("Geografia",8,1)],
        'NicolaSpina':[("Matematica",7.5,2),("Italiano",6,2),("Inglese",4,3),("Storia",8.5,2),("Geografia",8,2)]
    }
    return render(request,"view_c.html",context)
def lista_materie(request):
    lista={
        'm1':"Matematica",
        'm2':"Italiano",
        'm3':"Inglese",
        'm4':"Storia",
        'm5':"Geografia"
    }
    response= JsonResponse(lista)
    return response
def json_version(request):
    return render(request,"json_version.html")

seconda_app/views.py
from django.shortcuts import render
import datetime
# Create your views here.
def es_if(request):
    context={
        'var1':200,
        'var2':200,
        'var3':300,
    }
    return render(request,"es_if.html",context)
def if_else_elif(request):
    context={
        'var1':100,
        'var2':100.0,
        'var3':100.50,
    }
    return render(request,"if_else_elif.html",context)
def es_for(request):
    context={
        'list1':[1,datetime.date(2019,7,16),'Do not give up!'],
        'list2':[1,datetime.date(2019,7,16),'Do not give up!'],
    }
    return render(request,"es_for.html",context)

JSgames/templates/chessGame.html
{% extends "base.html"%}
{%load static%}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Scacchi</title>
    {% block scripts %}
    {% comment "popup" %}------------------------------------------------------------------------------------------------{% endcomment %}
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10.10.1/dist/sweetalert2.all.min.js"></script>
    <link rel='stylesheet' href='https://cdn.jsdelivr.net/npm/sweetalert2@10.10.1/dist/sweetalert2.min.css'>
    {% comment "chessboard" %}------------------------------------------------------------------------------------------------{% endcomment %}
    <link rel="stylesheet" href="{% static 'chessboard/css/chessboard.css'%}">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"
        integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous">
    </script>
    <script src="{%static 'chessboard/js/chessboard-1.0.0.min.js'%}">
    </script>
    {% comment "" %}------------------------------------------------------------------------------------------------{% endcomment %}
    {% endblock scripts %}
</head>

<body>
    {% block content %}
    <div id="myBoard" style="width:500px"></div>

    <script type="module">
        import Chess from "{% static "chess/chess.js" %}"
        //SCRIPT BOT SCACCHI----------------------------------
        var board = null
        var game = new Chess()
        
        function onDragStart(source, piece, position, orientation) {
            // do not pick up pieces if the game is over
            if (game.game_over()) return false

            // only pick up pieces for White
            if (piece.search(/^b/) !== -1) return false
        }

        function makeRandomMove() {
            var possibleMoves = game.moves()

            // game over
            if (possibleMoves.length === 0) return

            var randomIdx = Math.floor(Math.random() * possibleMoves.length)
            game.move(possibleMoves[randomIdx])
            board.position(game.fen())
        }

        function onDrop(source, target) {
            // see if the move is legal
            var move = game.move({
                from: source,
                to: target,
                promotion: 'q' // NOTE: always promote to a queen for example simplicity
            })

            // illegal move
            if (move === null) return 'snapback'

            // make random legal move for black
            window.setTimeout(makeRandomMove, 250)
        }

        // update the board position after the piece snap
        // for castling, en passant, pawn promotion
        function onSnapEnd() {
            board.position(game.fen())
        }

        var config = {
            draggable: true,
            position: 'start',
            onDragStart: onDragStart,
            onDrop: onDrop,
            onSnapEnd: onSnapEnd
        }
        board = Chessboard('myBoard', config)
        document.getElementById("myBoard").addEventListener('click', function(){
            if (game.game_over() == 1){
                Swal.fire("Parità", "Non sono state catturate pedine negli ultimi 50 turni", "warning");
            }else if (game.game_over()[0] == 2){
                let vincitore=game.game_over()[1];
                if(vincitore=='b')
                    vincitore='Bianco';
                else
                    vincitore='Nero'
                Swal.fire("Vittoria giocatore "+vincitore, "Scacco Matto", "success");
            }else if (game.game_over() == 3){
                Swal.fire("Parità ", "Stallo", "warning");
            }else if (game.game_over() == 4){
                Swal.fire("Parità", "Materiale Insufficiente", "warning");
            }else if (game.game_over() == 5){
                Swal.fire("Parità", "Ripetizione", "warning");
            }
          });
        //-------------------------------------------------------------------
    </script>
    {% endblock content %}
</body>

</html>

news/templates/articolo_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% extends 'base.html' %}
    {% block title %}
        {{articolo.titolo}}
    {% endblock title %}

    {% block content %}
        <h1>{{articolo.titolo}}</h1>
        <h3>{{articolo.contenuto}}</h3>
        <h5>Autore: {{articolo.giornalista}}</h5>
    {% endblock content %}
</body>
</html>

news/templates/giornalista_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% extends 'base.html' %}
    {% block title %}
        {{giornalista.nome}}
    {% endblock title %}

    {% block content %}
        <h1>{{giornalista.nome}}</h1>
        <h3>{{giornalista.cognome}}</h3>
    {% endblock content %}
</body>
</html>

news/templates/homeNews.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% extends 'base.html' %}
    {% block title %}
        Articoli e Giornalisti
    {% endblock title %}
    {% block content %}
        <h4>Articoli:</h4>
        {% for articolo in articoli %}
            <p><strong>Titolo: </strong>{{articolo.titolo}}</p>
            <p><strong>Contenuto: </strong>{{articolo.contenuto}}</p>
            <p><strong>Autore: </strong>{{articolo.giornalista}}</p>
            <hr>
        {% endfor %}
        <h4>Giornalisti</h4>
        {% for giornalista in giornalisti %}
            <p><strong>Nome: </strong>{{giornalista.nome}}</p>
            <p><strong>Cognome: </strong>{{giornalista.cognome}}</p>
            <hr>
        {% endfor %}
    {% endblock content %}
</body>
</html>

news/templates/lista_articoli.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lista Articoli</title>
</head>
<body>
    {% extends 'base.html' %}
    {% block title %}
        Lista Articoli
    {% endblock title %}
    {% block content %}
        <h4>Articoli:</h4>
        {% for articolo in articoli %}
            <p><strong>Titolo: </strong><a href="/news/articoli/{{articolo.id}}">{{articolo.titolo}}</a></p>
            <p><strong>Contenuto: </strong>{{articolo.contenuto}}</p>
            <p><strong>Autore: </strong>{{articolo.giornalista}}</p>
            <hr>
        {% endfor %}
    {% endblock content %}
</body>
</html>

news/templates/lista_giornalisti.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lista Giornalisti</title>
</head>
<body>
    {% extends 'base.html' %}
    {% block title %}
        Lista Giornalisti
    {% endblock title %}
    {% block content %}
        <h4>Giornalisti:</h4>
        {% for giornalista in giornalisti %}
            <p><strong>Nome: </strong><a href="/news/gionalisti/{{giornalista.id}}">{{giornalista.nome}}</a></p>
            <p><strong>Cognome: </strong>{{giornalista.cognome}}</p>
            <hr>
        {% endfor %}
    {% endblock content %}
</body>
</html>

prima_app/templates/chi_siamo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% extends 'base.html' %}

    {% block title %}{{block.super}}|Chi siamo{% endblock title %}

    {% block content %}
        <h1>Chi siamo</h1>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptate facilis quidem temporibus obcaecati, possimus cupiditate nisi exercitationem, quae tempore officia architecto nostrum nihil similique dolores, illo soluta neque iusto expedita!</p>
    {% endblock content %}
    
</body>
</html>

prima_app/templates/homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% extends 'base.html' %}

    {% block title %}{{block.super}}|Benvenuto{% endblock title %}

    {% block content %}
        <h1>Benvenuto</h1>
    {% endblock content %}
    
</body>
</html>

prima_app/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    {% extends 'base.html' %}

    {% block title %}{{block.super}}|Chi siamo{% endblock title %}

    {% block content %}
    <ol>
        <li><a href="{% url 'prima_app:homepage' %}">Homepage di benvenuto</a></li>
        <li><a href="{% url 'prima_app:lista' %}">Lista</a></li>
        <li><a href="{% url 'prima_app:chi_siamo' %}">Chi siamo</a></li>
        <li><a href="{% url 'prima_app:variabili' %}">Variabili</a></li>
        <li><a href="{% url 'prima_app:welcome' %}">Welcome</a></li>
        <li><a href="{% url 'seconda_app:es_for' %}">Es for</a></li>
        <li><a href="{% url 'seconda_app:es_if' %}">Es if</a></li>
        <li><a href="{% url 'seconda_app:if_else_elif' %}">If else elif</a></li>
    </ol>
    {% endblock content %}
</body>

</html>

prima_app/templates/lista.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
{% extends 'base.html' %}

    {% block title %}{{block.super}}|Lista{% endblock title %}

    {% block content %}
        <ol>
            <li>Primo elemento</li>
            <li>Secondo elemento</li>
            <li>Terzo elemento</li>
        </ol>
    {% endblock content %}
</body>
</html>

prima_app/templates/variabili.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
{% extends 'base.html' %}

    {% block title %}{{block.super}}|Varibili{% endblock title %}

    {% block content %}
        <ol>
            <li>{{var1}}</li>
            <li>{{var2}}</li>
            <li>{{var3}}</li>
        </ol>
    {% endblock content %}
    
</body>
</html>

prima_app/templates/welcome.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
{% extends 'base.html' %}

    {% block title %}{{block.super}}|Welcome{% endblock title %}

    {% block content %}
        <h1>welcome</h1>
    {% endblock content %}
    
</body>
</html>

prova_pratica_1/templates/json_version.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% extends 'base.html' %}

    {% block content %}
    <div id="content">
        <h2 style="margin-left:-50px">Materie:</h2>
    </div>
    <script>
        (async function() {
            const data= await fetch("{% url 'prova_pratica_1:lista_materie' %}")
            const ris=await data.json();
            document.getElementById("content").innerHTML+="<ul><li>"+ris['m1']+"</li><li>"+ris['m2']+"</li><li>"+ris['m3']+"</li><li>"+ris['m4']+"</li><li>"+ris['m5']+"</li></ul>";
        })();
    </script>
    {% endblock %}
</body>
</html>

prova_pratica_1/templates/view_b.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% extends 'base.html' %}

    {% block content %}
    <h2 style="margin-left:-50px">Materie:</h2>
        <ul>
            <li>{{m1}}</li>
            <li>{{m2}}</li>
            <li>{{m3}}</li>
            <li>{{m4}}</li>
            <li>{{m5}}</li>
        </ul>
    {% endblock %}
</body>
</html>

prova_pratica_1/templates/view_c.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% extends 'base.html' %}

    {% block content %}
        <ul>
            <h3 style="margin-left:-50px">Giuseppe Gullo:</h3>
            <li>{{GiuseppeGullo}}</li>
            <h3 style="margin-left:-50px">Antonio Barbera:</h3>
            <li>{{AntonioBarbera}}</li>
            <h3 style="margin-left:-50px">Nicola Spina:</h3>
            <li>{{NicolaSpina}}</li>
        </ul>
    {% endblock %}
</body>
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Index</title>
    
    
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous">
    </script>
    {% block scripts %}{% endblock scripts %}
</head>

<body>
    <div class="navigation">
        <ul>
            <li class="list active">
                <a href="/">
                    <span class="icon">
                        <ion-icon name="home-outline"></ion-icon>
                    </span>
                    <span class="text">Home</span>
                </a>
                <div class="dropdown-menu"></div>
            </li>
            <li class="list">
                <a href="#">
                    <span class="icon">
                        <ion-icon name="apps-outline"></ion-icon>
                    </span>
                    <span class="text">Prima App</span>
                </a>
                 <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'prima_app:homepage' %}">Homepage</a>
                    <a class="dropdown-item" href="{% url 'prima_app:chi_siamo' %}">Chi Siamo</a>
                    <a class="dropdown-item" href="{% url 'prima_app:index' %}">Index</a>
                    <a class="dropdown-item" href="{% url 'prima_app:lista' %}">Lista</a>
                    <a class="dropdown-item" href="{% url 'prima_app:variabili' %}">Variabili</a>
                    <a class="dropdown-item" href="{% url 'prima_app:welcome' %}">Welcome</a>
                  </div>
            </li>
            <li class="list">
                <a href="#">
                    <span class="icon">
                        <ion-icon name="apps-outline"></ion-icon>
                    </span>
                    <span class="text">Seconda App</span>
                </a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'seconda_app:es_for' %}">Es for</a>
                    <a class="dropdown-item" href="{% url 'seconda_app:es_if' %}">Es if</a>
                    <a class="dropdown-item" href="{% url 'seconda_app:if_else_elif' %}">If else elif</a>
                </div>
            </li>
            <li class="list">
                <a href="#">
                    <span class="icon">
                        <ion-icon name="apps-outline"></ion-icon>
                    </span>
                    <span class="text">News</span>
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'news:lista_articoli' %}">Articoli</a>
                    <a class="dropdown-item" href="{% url 'news:lista_giornalisti' %}">Giornalisti</a>
                  </div>
            </li>
            <li class="list">
                <a href="#">
                    <span class="icon">
                        <ion-icon name="game-controller-outline"></ion-icon>
                    </span>
                    <span class="text">Games</span>
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'JSgames:chessGame' %}">Scacchi</a>
                </div>
            </li>
            <li class="list">
                <a href="#">
                    <span class="icon">
                        <ion-icon name="document-outline"></ion-icon>
                    </span>
                    <span class="text">Prova Pratica 1</span>
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'prova_pratica_1:view_b' %}">View B</a>     
                    <a class="dropdown-item" href="{% url 'prova_pratica_1:view_c' %}">View C</a>
                    <a class="dropdown-item" href="{% url 'prova_pratica_1:json_version' %}">Json Version</a>
                </div>
            </li>
            <li class="list">
                <a href="#">
                    <span class="icon">
                        <ion-icon name="document-outline"></ion-icon>
                    </span>
                    <span class="text">API</span>
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'prova_pratica_1:lista_materie' %}">Lista Materie</a>     
                </div>
            </li>
            <div class="indicator"></div>
        </ul>
    </div>
    <br>
    <div class="container-content">
    <div class="container my-4">
        {% block content %}{% endblock content %}
    </div>
    </div>
    <script>
        const list = document.querySelectorAll('.list');
        function activelink() {
            Array.from(document.getElementsByClassName('dropdown-menu')).forEach((itemD) =>
            itemD.hidden=true);

            Array.from(document.getElementsByClassName('dropdown-menu')).forEach((itemD) =>
            itemD.hidden=true);

            list.forEach((item) =>
                item.classList.remove('active'));
            this.classList.add('active');
            document.getElementsByClassName('list active').item(0).children[1].hidden=false;
        }
        list.forEach((item) =>
            item.addEventListener('click', activelink));
        Array.from(document.getElementsByClassName('dropdown-menu')).forEach((itemD) =>
            itemD.hidden=true);
    </script>
</body>

</html>